"""
Visualization module using py3Dmol.

Provides:
    show_molecule(molecule)
"""

import py3Dmol


def show_molecule(molecule, style="stick", width=500, height=400):
    """
    Visualize a Molecule object in Jupyter Notebook using py3Dmol.

    Parameters
    ----------
    molecule : Molecule
        Molecule object containing Atoms with coordinates.
    style : str
        One of: "stick", "sphere", "line", "ballstick"
    width : int
        Viewer width in pixels.
    height : int
        Viewer height in pixels.
    """

    # Build an XYZ string for py3Dmol
    xyz = f"{len(molecule.atoms)}\nGenerated by molecule_project\n"
    for atom in molecule.atoms:
        x, y, z = atom.coords
        xyz += f"{atom.symbol} {x:.6f} {y:.6f} {z:.6f}\n"

    view = py3Dmol.view(width=width, height=height)
    view.addModel(xyz, "xyz")

    # Choose drawing style
    if style == "stick":
        view.setStyle({"stick": {}})
    elif style == "sphere":
        view.setStyle({"sphere": {"scale": 0.3}})
    elif style == "line":
        view.setStyle({"line": {}})
    elif style == "ballstick":
        view.setStyle({"stick": {}, "sphere": {"scale": 0.3}})
    else:
        view.setStyle({"stick": {}})

    view.zoomTo()
    return view.show()

